name: smart_parking_app
description: A Smart Parking System Flutter Application

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  crypto: ^3.0.1
  encrypt: ^5.0.0
  intl: ^0.17.0
  flutter_lints: ^2.0.0
  geolocator: ^10.1.0
  provider: ^6.1.1
  flutter_map: ^6.0.0
  latlong2: ^0.9.1
  flutter_polyline_points: 2.1.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^17.0.0
  #workmanager: ^0.5.2
  flutter_countdown_timer: ^4.1.0
  permission_handler: ^11.0.1
  image_picker: 

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/static/Cairo-Regular.ttf
  assets:
    - assets/fonts/
    - assets/images/logo.png


